### ISSUE TITLE
Dragging often doesn't catch, needs to be more consistent

### ISSUE THREAD

**Issue by batjko** [olmokramer/atom-move-status-items#3]
It sort of works now... But not consistently.
It seems to work better when I move stuff to the right, less likely when I try to do it to the left. But it's difficult either way.

A bit lengthy gif to demonstrate:
![http://i.imgur.com/bzgnwET.gif](http://i.imgur.com/bzgnwET.gif)

**Comment by olmokramer** [comment]
I think I found the cause of this issue. It was impossible to move the first or last item around... v0.0.7 published. Please let me know if it works.

**Comment by batjko** [comment]
Not published yet?
It's still on 0.0.6, even in your repo.

**Comment by olmokramer** [comment]
Ooops, forgot to publish... Should be up now.

**Comment by batjko** [comment]
Yup, that part works now. Thanks.
But...
https://github.com/olmokramer/atom-move-status-items/issues/4
