### ISSUE TITLE
Handling links in status bar not quite working

### ISSUE THREAD

**Issue by batjko** [olmokramer/atom-move-status-items#4]
So sorry:

When I grab links they have a different action, a different drag cursor, and when I let go and move the mouse left and right, your package hasn't noticed that I have let go. Instead the items keep shifting as I move the mouse left and right.

![http://i.imgur.com/rxkNm4j.gif](http://i.imgur.com/rxkNm4j.gif)

And if I then click again (to try and shake the sticky behavior off), The red error galore starts happening again:

![image](https://cloud.githubusercontent.com/assets/7287076/8505620/7bd301aa-21e3-11e5-9d87-51c5a33fbc97.png)

**Comment by olmokramer** [comment]
Oh, right... Links... Think I found the issue. Thanks!

**Comment by batjko** [comment]
Yup, smooth operation.
